"""
Trade-CLI Analysis Schema - Dataclasses

Defines the core data structures for analysis, engine outputs, and verdicts.
All analysis flows through these structures to ensure consistency and auditability.

Phase 1: Frozen schema (do not modify without migration)
Date: 2025-04-30
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import List, Optional, Dict, Any
from enum import Enum
import json
import uuid


# ============================================================================
# ENUMS
# ============================================================================

class BiaType(str, Enum):
    """Market bias classification"""
    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"
    FRAGILE = "fragile"  # directionally biased but weak


class VerdictType(str, Enum):
    """RiskGuardian verdict on whether to trade"""
    ALLOWED = "allowed"           # Pass all checks
    WATCH_ONLY = "watch_only"     # Monitor but don't trade (quality issues)
    BLOCKED = "blocked"            # Veto by RiskGuardian (rule violation)


class ExecutionQuality(str, Enum):
    """Quality of trade execution"""
    IDEAL = "ideal"
    ACCEPTABLE = "acceptable"
    POOR = "poor"
    NOT_TRADED = "not_traded"


class AnalysisType(str, Enum):
    """Type of analysis"""
    THESIS = "thesis"
    EDUCATIONAL = "educational"
    TEST = "test"
    BACKTEST = "backtest"


# ============================================================================
# ENGINE OUTPUT (Individual Motor)
# ============================================================================

@dataclass
class EngineOutput:
    """
    Output from a single analytical engine (Technical, PriceAction, Fundamental).
    
    Each motor produces: score, explanation, and evidence used.
    """
    
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    
    # Identification
    engine_name: str = ""               # "technical", "price_action", "fundamental"
    engine_version: str = "1.0"         # For tracking motor improvements
    
    # Result
    score: float = 0.0                  # 0.0 to 1.0
    explanation: str = ""               # Why this score?
    
    # Evidence (structured data used)
    evidence: Dict[str, Any] = field(default_factory=dict)  # Technical indicators, MA values, etc.
    
    # Conflict tracking
    conflict_with_other: bool = False
    conflict_description: str = ""
    
    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    # Validation
    def __post_init__(self):
        """Validate score range"""
        if not 0.0 <= self.score <= 1.0:
            raise ValueError(f"Engine score must be 0.0-1.0, got {self.score}")
        if not self.engine_name:
            raise ValueError("engine_name is required")
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary (JSON-compatible)"""
        d = asdict(self)
        d['created_at'] = self.created_at.isoformat()
        return d
    
    def to_json(self) -> str:
        """Serialize to JSON"""
        return json.dumps(self.to_dict(), default=str)


# ============================================================================
# ANALYSIS OUTPUT (Synthesized from Engines)
# ============================================================================

@dataclass
class AnalysisOutput:
    """
    Main analysis output structure. This is what gets stored in SQLite
    and displayed to the user.
    
    Generated by ThesisEngine (synthesizes motor outputs).
    Passed to RiskGuardian for verdict.
    """
    
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    
    # ---- IDENTIFICATION ----
    symbol: str = ""                    # "NZDUSD", "EURUSD", etc.
    timeframe: str = ""                 # "M5", "M15", "H1", "H4"
    analysis_type: AnalysisType = AnalysisType.THESIS
    
    # ---- CLASSIFICATION ----
    bias: BiaType = BiaType.NEUTRAL
    setup_type: str = ""                # "liquidity_sweep_reclaim", "pullback_continuation", etc.
    
    # ---- CONFIDENCE ----
    confidence_score: float = 0.0       # 0.0-1.0: How confident is this analysis?
    alignment_score: float = 0.0        # 0.0-1.0: How much do motors agree?
    
    # ---- INDIVIDUAL ENGINE SCORES ----
    technical_score: float = 0.0        # 0.0-1.0
    price_action_score: float = 0.0     # 0.0-1.0
    fundamental_score: float = 0.0      # 0.0-1.0
    # Note: Other scores (intermarket, sentiment, volume, etc.) added in Phase 2+
    
    # ---- DECISION RATIONALE ----
    invalidations: List[str] = field(default_factory=list)
    """Conditions that would kill this thesis. E.g., ["M15 close below X", "macro event in 20m"]"""
    
    risk_notes: List[str] = field(default_factory=list)
    """Risk factors. E.g., ["spread elevated", "USD intermarket mixed"]"""
    
    # ---- VERDICT (From RiskGuardian) ----
    verdict: VerdictType = VerdictType.WATCH_ONLY
    veto_reason: Optional[str] = None
    """Why was it vetoed? (populated by RiskGuardian)"""
    
    # ---- TIMESTAMPS ----
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    # ---- EXTERNAL LINKS ----
    obsidian_link: Optional[str] = None  # [[2025-04-30-NZDUSD-M15-thesis]]
    
    # ---- ANALYST NOTES ----
    analyst_notes: str = ""
    
    # Validation
    def __post_init__(self):
        """Validate ranges and required fields"""
        if not self.symbol:
            raise ValueError("symbol is required")
        if not self.timeframe:
            raise ValueError("timeframe is required")
        if not 0.0 <= self.confidence_score <= 1.0:
            raise ValueError("confidence_score must be 0.0-1.0")
        if not 0.0 <= self.alignment_score <= 1.0:
            raise ValueError("alignment_score must be 0.0-1.0")
        if not 0.0 <= self.technical_score <= 1.0:
            raise ValueError("technical_score must be 0.0-1.0")
        if not 0.0 <= self.price_action_score <= 1.0:
            raise ValueError("price_action_score must be 0.0-1.0")
        if not 0.0 <= self.fundamental_score <= 1.0:
            raise ValueError("fundamental_score must be 0.0-1.0")
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary (JSON-compatible)"""
        return {
            'id': self.id,
            'symbol': self.symbol,
            'timeframe': self.timeframe,
            'analysis_type': self.analysis_type.value,
            'bias': self.bias.value,
            'setup_type': self.setup_type,
            'confidence_score': self.confidence_score,
            'alignment_score': self.alignment_score,
            'technical_score': self.technical_score,
            'price_action_score': self.price_action_score,
            'fundamental_score': self.fundamental_score,
            'invalidations': self.invalidations,
            'risk_notes': self.risk_notes,
            'verdict': self.verdict.value,
            'veto_reason': self.veto_reason,
            'created_at': self.created_at.isoformat(),
            'obsidian_link': self.obsidian_link,
            'analyst_notes': self.analyst_notes,
        }
    
    def to_json(self) -> str:
        """Serialize to JSON"""
        return json.dumps(self.to_dict(), default=str)
    
    @staticmethod
    def from_dict(data: Dict[str, Any]) -> 'AnalysisOutput':
        """Deserialize from dictionary"""
        # Convert enums
        if isinstance(data.get('bias'), str):
            data['bias'] = BiaType(data['bias'])
        if isinstance(data.get('analysis_type'), str):
            data['analysis_type'] = AnalysisType(data['analysis_type'])
        if isinstance(data.get('verdict'), str):
            data['verdict'] = VerdictType(data['verdict'])
        
        # Remove created_at string if present (will be re-created)
        if 'created_at' in data and isinstance(data['created_at'], str):
            data.pop('created_at')
        
        return AnalysisOutput(**data)
    
    @staticmethod
    def from_json(json_str: str) -> 'AnalysisOutput':
        """Deserialize from JSON"""
        data = json.loads(json_str)
        return AnalysisOutput.from_dict(data)


# ============================================================================
# PROPOSAL VERDICT (RiskGuardian Output)
# ============================================================================

@dataclass
class ProposalVerdictOutput:
    """
    RiskGuardian's final decision on whether to trade.
    
    This is the "NO" layer that prevents bad trades from happening.
    """
    
    # Decision
    verdict: VerdictType
    
    # Reasoning
    reason: str                         # Why this verdict?
    violated_rules: List[str] = field(default_factory=list)
    """Which FTMO rules were violated (if any)?"""
    
    # Debugging/Logging
    checks_passed: Dict[str, bool] = field(default_factory=dict)
    """Which checks passed/failed? E.g., {'drawdown_ok': True, 'risk_ok': False}"""
    
    # Timestamp
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'verdict': self.verdict.value,
            'reason': self.reason,
            'violated_rules': self.violated_rules,
            'checks_passed': self.checks_passed,
            'created_at': self.created_at.isoformat(),
        }
    
    def to_json(self) -> str:
        """Serialize to JSON"""
        return json.dumps(self.to_dict(), default=str)


# ============================================================================
# ANALYSIS OUTCOME (Post-Trade)
# ============================================================================

@dataclass
class AnalysisOutcome:
    """
    Records what actually happened after an analysis.
    Used for post-mortem and learning.
    """
    
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    analysis_id: str = ""               # Links to AnalysisOutput.id
    
    # What happened
    price_action: str = ""              # Description of price movement
    price_moved_pips: int = 0
    
    # Was the thesis right?
    invalidated: bool = False
    invalidation_type: Optional[str] = None
    
    # Operational result (if traded)
    profit_loss_pips: Optional[int] = None
    execution_quality: ExecutionQuality = ExecutionQuality.NOT_TRADED
    
    # Analysis
    post_mortem_notes: str = ""
    
    # Link to post-mortem doc
    obsidian_link: Optional[str] = None
    
    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    outcome_timestamp: Optional[datetime] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'id': self.id,
            'analysis_id': self.analysis_id,
            'price_action': self.price_action,
            'price_moved_pips': self.price_moved_pips,
            'invalidated': self.invalidated,
            'invalidation_type': self.invalidation_type,
            'profit_loss_pips': self.profit_loss_pips,
            'execution_quality': self.execution_quality.value,
            'post_mortem_notes': self.post_mortem_notes,
            'obsidian_link': self.obsidian_link,
            'created_at': self.created_at.isoformat(),
            'outcome_timestamp': self.outcome_timestamp.isoformat() if self.outcome_timestamp else None,
        }
    
    def to_json(self) -> str:
        """Serialize to JSON"""
        return json.dumps(self.to_dict(), default=str)


# ============================================================================
# EXAMPLE USAGE (for testing)
# ============================================================================

if __name__ == "__main__":
    # Create engine outputs
    technical_output = EngineOutput(
        engine_name="technical",
        score=0.70,
        explanation="Trend up on H1, support at 0.5850",
        evidence={"trend": "bullish", "support": 0.5850}
    )
    
    price_action_output = EngineOutput(
        engine_name="price_action",
        score=0.55,
        explanation="Candle pattern ambiguous",
        evidence={"pattern": "indecision"}
    )
    
    # Create analysis (synthesized from engines)
    analysis = AnalysisOutput(
        symbol="NZDUSD",
        timeframe="M15",
        bias=BiaType.BULLISH,
        setup_type="liquidity_sweep_reclaim",
        confidence_score=0.68,
        alignment_score=0.61,
        technical_score=0.70,
        price_action_score=0.55,
        fundamental_score=0.65,
        invalidations=["M15 close below 0.5850", "macro event in 20m"],
        risk_notes=["spread elevated", "USD intermarket mixed"],
        analyst_notes="Looks promising but context fragile"
    )
    
    # RiskGuardian's verdict
    verdict = ProposalVerdictOutput(
        verdict=VerdictType.WATCH_ONLY,
        reason="Alignment below threshold (61% < 70%)",
        violated_rules=["min_alignment_score"],
        checks_passed={
            "drawdown_ok": True,
            "risk_ok": True,
            "news_ok": True,
            "alignment_ok": False,
        }
    )
    
    # Example output
    print("=" * 50)
    print("ANALYSIS OUTPUT (JSON)")
    print("=" * 50)
    print(analysis.to_json())
    print("\n")
    print("=" * 50)
    print("RISK GUARDIAN VERDICT")
    print("=" * 50)
    print(verdict.to_json())
